export const slides = Object.freeze([
  { id: 'capa', title: 'Voto Consciente Pernambuco', section: 'Abertura', estimatedSeconds: 30, notes: 'Apresente o projeto e a equipe de forma breve.' },
  { id: 'pergunta-candidaturas', title: 'Pergunta ao público 1', section: 'Abertura', estimatedSeconds: 35, notes: 'Ouça dois ou três palpites antes de revelar o número.', revealSteps: 1 },
  { id: 'pergunta-leitura', title: 'Pergunta ao público 2', section: 'Abertura', estimatedSeconds: 35, notes: 'Diferencie intenção de voto e leitura documental.', revealSteps: 1 },
  { id: 'pergunta-comparacao', title: 'Pergunta ao público 3', section: 'Abertura', estimatedSeconds: 45, notes: 'Revele o volume somente depois das respostas.', revealSteps: 1 },
  { id: 'escala', title: 'A escala do desafio', section: 'Problema', estimatedSeconds: 35, notes: 'Mostre que o esforço de leitura cresce rapidamente.' },
  { id: 'problema', title: 'O problema', section: 'Problema', estimatedSeconds: 35, notes: 'Percorra os cinco obstáculos sem alongar.' },
  { id: 'evidencias', title: 'Evidências da necessidade', section: 'Pesquisa', estimatedSeconds: 55, notes: 'Separe claramente pesquisa própria e contexto externo.' },
  { id: 'objetivo', title: 'Pergunta de pesquisa e objetivo', section: 'Pesquisa', estimatedSeconds: 35, notes: 'Reforce que a ferramenta não recomenda voto.' },
  { id: 'dados', title: 'Dados utilizados', section: 'Método', estimatedSeconds: 45, notes: 'Os números vêm da auditoria atual do repositório.' },
  { id: 'preparacao', title: 'Como os dados foram preparados', section: 'Método', estimatedSeconds: 45, notes: 'Apresente o agente de IA generativa como baseado no Gemini, operado em notebook e supervisionado pela equipe. Reforce que ele foi usado somente antes da publicação.' },
  { id: 'perguntas', title: 'Como as perguntas foram criadas', section: 'Método', estimatedSeconds: 55, notes: 'Explique neutralidade, limites de rastreabilidade e responsabilidade final da equipe.' },
  { id: 'arquitetura', title: 'Arquitetura e tecnologias', section: 'Tecnologia', estimatedSeconds: 45, notes: 'Identifique Gemini em ambiente de notebook como tecnologia do agente e separe a preparação offline do cálculo determinístico.' },
  { id: 'limitacoes', title: 'Limitações', section: 'Encerramento', estimatedSeconds: 45, notes: 'Apresente as limitações como parte da transparência.' },
  { id: 'conclusao', title: 'Conclusão', section: 'Encerramento', estimatedSeconds: 55, notes: 'Finalize com a mensagem principal e convide a banca a acessar o MVP pelo QR Code ou pelo endereço visível.' },
]);
