export const slides = Object.freeze([
  { id: 'capa', title: 'Voto Consciente Pernambuco', section: 'Abertura', estimatedSeconds: 30, notes: 'Apresente o projeto e a equipe de forma breve.' },
  { id: 'pergunta-candidaturas', title: 'Pergunta ao público 1', section: 'Abertura', estimatedSeconds: 35, notes: 'Ouça dois ou três palpites antes de revelar o número.', revealSteps: 1 },
  { id: 'pergunta-leitura', title: 'Pergunta ao público 2', section: 'Abertura', estimatedSeconds: 35, notes: 'Diferencie intenção de voto e leitura documental.', revealSteps: 1 },
  { id: 'pergunta-comparacao', title: 'Pergunta ao público 3', section: 'Abertura', estimatedSeconds: 45, notes: 'Revele o volume somente depois das respostas.', revealSteps: 1 },
  { id: 'escala', title: 'A escala do desafio', section: 'Problema', estimatedSeconds: 35, notes: 'Mostre que o esforço de leitura cresce rapidamente.' },
  { id: 'problema', title: 'O problema', section: 'Problema', estimatedSeconds: 35, notes: 'Percorra os cinco obstáculos sem alongar.' },
  { id: 'evidencias', title: 'Evidências da necessidade', section: 'Pesquisa', estimatedSeconds: 55, notes: 'Separe claramente pesquisa própria e contexto externo.' },
  { id: 'objetivo', title: 'Pergunta de pesquisa e objetivo', section: 'Pesquisa', estimatedSeconds: 35, notes: 'Reforce que a ferramenta não recomenda voto.' },
  { id: 'dados', title: 'Dados utilizados', section: 'Método', estimatedSeconds: 45, notes: 'Os números vêm da auditoria atual do repositório.' },
  { id: 'preparacao', title: 'Como os dados foram preparados', section: 'Método', estimatedSeconds: 45, notes: 'Destaque o encadeamento e a revisão humana.' },
  { id: 'perguntas', title: 'Como as perguntas foram criadas', section: 'Método', estimatedSeconds: 55, notes: 'Explique neutralidade, rastreabilidade e limites da IA.' },
  { id: 'questionario', title: 'Questionário e importância', section: 'Produto', estimatedSeconds: 45, notes: 'Mostre como o peso altera a influência de cada tema.' },
  { id: 'motor', title: 'Motor matemático', section: 'Produto', estimatedSeconds: 55, notes: 'Faça a conta em voz alta: quatro de seis.' },
  { id: 'cobertura', title: 'Correspondência e cobertura', section: 'Produto', estimatedSeconds: 45, notes: 'Uma porcentagem sem cobertura pode induzir leitura incompleta.' },
  { id: 'arquitetura', title: 'Arquitetura e tecnologias', section: 'Tecnologia', estimatedSeconds: 45, notes: 'Separe preparação assistida de cálculo determinístico.' },
  { id: 'demo', title: 'Demonstração do MVP', section: 'Demonstração', estimatedSeconds: 240, notes: 'Abra o MVP, responda alguns temas e retorne a este slide.' },
  { id: 'limitacoes', title: 'Limitações', section: 'Encerramento', estimatedSeconds: 45, notes: 'Apresente as limitações como parte da transparência.' },
  { id: 'conclusao', title: 'Conclusão', section: 'Encerramento', estimatedSeconds: 35, notes: 'Finalize com a mensagem principal e convide para acessar.' },
]);
